[versions]
minecraft = "26.1.2"
architectury-api = "20.0.5"
fabric-loader = "0.19.3"
neoforge = "26.1.2.74"
loom-plugin = "1.14-SNAPSHOT"
architectury-plugin = "3.5-SNAPSHOT"
shadow-plugin = "9.4.2"
yacl-fabric = "3.9.4+26.1-fabric"
yacl-neoforge = "3.9.4+26.1-neoforge"
modmenu = "18.0.0-beta.1"

[libraries]
minecraft = { module = "net.minecraft:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
architectury = { module = "dev.architectury:architectury", version.ref = "architectury-api" }
architectury-fabric = { module = "dev.architectury:architectury-fabric", version.ref = "architectury-api" }
architectury-neoforge = { module = "dev.architectury:architectury-neoforge", version.ref = "architectury-api" }
neoforge = { module = "net.neoforged:neoforge", version.ref = "neoforge" }
yacl-fabric = { module = "dev.isxander:yet-another-config-lib", version.ref = "yacl-fabric" }
yacl-neoforge = { module = "dev.isxander:yet-another-config-lib", version.ref = "yacl-neoforge" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }

[plugins]
loom = { id = "dev.architectury.loom-no-remap", version.ref = "loom-plugin" }
architectury = { id = "architectury-plugin", version.ref = "architectury-plugin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow-plugin" }
