modLoader = "javafml"
loaderVersion = "[4,)"
license = "${modLicense}"
clientSideOnly = false

[[mods]]
modId = "heartfall"
version = "${version}"
displayName = "${modName}"
description = "${modDescription}"
authors = "${modAuthor}"
logoFile = "assets/heartfall/icon.png"

[[dependencies.heartfall]]
modId = "neoforge"
type = "required"
versionRange = "[26.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.heartfall]]
modId = "minecraft"
type = "required"
versionRange = "[26.1,)"
ordering = "NONE"a
side = "BOTH"

[[dependencies.heartfall]]
modId = "architectury"
type = "required"
versionRange = "[20.0,)"
ordering = "AFTER"
side = "BOTH"
